# permissions for end users to view accountiams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: accountiam-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-user-management-operator
    app.kubernetes.io/part-of: ibm-user-management-operator
    app.kubernetes.io/managed-by: kustomize
  name: accountiam-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - accountiams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - accountiams/status
  verbs:
  - get
