apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ibm-user-management-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AccountIAM is the Schema for the accountiams API
      displayName: Account IAM
      kind: AccountIAM
      name: accountiams.operator.ibm.com
      version: v1alpha1
  description: You can use IBM User Management Operator to install the Account IAM
    services to manage user access to IBM services
  displayName: IBM User Management Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IBM
  - Cloud
  - Account-IAM
  - User-Management
  links:
  - name: Ibm User Management Operator
    url: https://ibm-user-management-operator.domain
  maintainers:
  - email: test@email.com
    name: test
  maturity: alpha
  provider:
    name: IBM
  version: 0.0.0
